app/models.py
from flask_login import UserMixin
from werkzeug.security import check_password_hash, generate_password_hash
from .extensions import db
from datetime import datetime


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50), unique=True, nullable=False)
    password = db.Column(db.String(50), nullable=False)
    post = db.relationship("Post", backref="post", lazy=True, cascade="all, delete")

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    content = db.Column(db.Text, nullable=False)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)
#    author = db.relationship("User", backref='author')

app/__init__.py
from flask import Flask
from .extensions import db, login_manager
from .config import Config


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    #reqister blueprints 
    from .routes.index import index_bp
    app.register_blueprint(index_bp)

    from .routes.auth import auth_bp
    app.register_blueprint(auth_bp)

    from .routes.post import post_bp
    app.register_blueprint(post_bp)
    
    #login manager init
    login_manager.init_app(app)
    login_manager.login_view = 'auth.sign_in'

    from .models import User
    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(user_id)
    
    #init db 
    db.init_app(app)
    with app.app_context():
        db.create_all()
    return app

app/routes/auth.py
from flask import Blueprint, redirect, url_for, request, render_template
from flask_login import login_user, logout_user, login_required, current_user
from ..models import User, db 
from ..utils import validate_username, validate_password


auth_bp = Blueprint("auth", __name__, url_prefix='/auth')


@auth_bp.route("/sign-up", methods=['GET', 'POST'])
def sign_up():
    if current_user.is_authenticated:
        redirect(url_for("index.index"))
    
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        username = username.strip().lower()

        if not username or not password:
            return render_template("error.html")
        
        if User.query.filter_by(username=username).first():
            return render_template("error.html")
        
        if validate_username(username) or validate_password(password):
            return render_template("error.html")

        new_user = User(username=username)
        new_user.set_password(password)
        db.session.add(new_user)
        db.session.commit()

        user = User.query.filter_by(username=username).first()
        login_user(user, remember=True)

        return redirect(url_for('index.index'))

    return render_template('sign-up.html')


@auth_bp.route("/sign-in", methods=['GET', 'POST'])
def sign_in():
    if current_user.is_authenticated:
        redirect(url_for("index.index"))
    
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        username = username.strip().lower()

        user = User.query.filter_by(username=username).first()
        if user and user.check_password(password):
            login_user(user, remember=True)
            return redirect(url_for("index.index"))
        return render_template("error.html")

    return render_template("sign-in.html")

@auth_bp.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("index.index"))

app/routes/index.py
from flask import Blueprint, render_template
from ..models import Post, User

index_bp = Blueprint("index", __name__)

@index_bp.route("/")
@index_bp.route("/page/<int:page>")
def index(page=1):
    posts = Post.query.order_by(Post.timestamp.desc()).paginate(page=page, per_page=5, error_out=False)
    return render_template("index.html", posts=posts, user=User)

app/routes/post.py
from flask import Blueprint, request, url_for, render_template, redirect
from flask_login import login_required, current_user
from ..models import db, Post, User

post_bp = Blueprint("post", __name__)

@post_bp.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    if request.method == 'POST':
        title = request.form.get('title').strip()
        content = request.form.get('content').strip()

        if not title or not content:
            return render_template("error.html")
        
        post = Post(title=title, content=content, user_id=current_user.id)
        db.session.add(post)
        db.session.commit()
        
        return redirect(url_for('index.index'))
         
    return render_template("new-post.html")


@post_bp.route("/post/<int:id>")
def post_page(id):
    post = Post.query.get(id)
    if not post:
        return render_template("error.html")
    
    author = User.query.get(post.user_id)
    return render_template("post.html", post=post, author=author)

@post_bp.route("/post/publications/<int:page>")
@post_bp.route("/post/publications")
def publications(page=1):
    posts = Post.query.filter_by(user_id=current_user.id).paginate(page=page, per_page=5, error_out=False)
    return render_template("publications.html", posts=posts)

app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    </head>
    <body>
        <header>
            <p><b>Neolog</b></p>
            <a href="{{ url_for('index.index') }}">Index</a>
            {% if current_user.is_authenticated %}
                <a href="{{ url_for('auth.logout') }}">Logout</a>
            {% else %}
                <a href="{{ url_for('auth.sign_in') }}">Login</a>
            {% endif %}
            {% if current_user.is_authenticated %}
                <a href="{{ url_for('post.publications')}}">Publications</a>
                <a href="{{ url_for('post.new_post') }}">New post</a>
            {% endif %}
        </header>

        <div class="container">
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

app/templates/error.html
{% extends "base.html" %}

{% block title %}Error{% endblock %}

{% block content %}
<h2>SOMETHING WENT WRONG...</h2>
<a href="{{ url_for('index.index') }}">Home</a>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %} NeoLog - Index Page {% endblock %}

{% block content %}
{% for post in posts.items %}
    <div class="post">
        <h4>{{ post.title }}</h4>
        <p>
            {{ post.content[:100] }}
            <a href="{{ url_for('post.post_page', id=post.id)}}">Read more</a>
        </p>
        <p> Author: {{ user.query.get(post.user_id).username }} </p>
    </div>
{% endfor %}
{% if posts.has_prev %}
    <a href="{{ url_for('index.index', page=posts.prev_num) }}">←</a>
{% endif %}
{% if posts.has_next %}
    <a href="{{ url_for('index.index', page=posts.next_num) }}">→</a>
{% endif %}
{% endblock %}

app/templates/new-post.html
{% extends "base.html" %}

{% block title %}New post{% endblock %}

{% block content %}
<h2>New post</h2>
<form method="post">
    <input type="text" name="title" placeholder="Title" required>
    <textarea name="content" placeholder="Content" required></textarea>
    <button type="submit">Publish</button>
</form>
{% endblock %}

app/templates/post.html
{% extends "base.html" %}

{% block title %}Neolog post{% endblock %}

{% block content %}
<h2>{{ post.title }}</h2>
<p>Author: <b>{{ author.username }}</b></p>
<p>{{ post.content }}</p>
{% endblock %}

app/templates/publications.html
{% extends "base.html" %}

{% block title %} Publications {% endblock %}

{% block content %}
<h2>{{ current_user.username }}</h2>
{% for post in posts.items %}
    <div class="post">
        <h4>{{ post.title }}</h4>
        <p>
            {{ post.content[:100] }}
            <a href="{{ url_for('post.post_page', id=post.id)}}">Read more</a>
        </p>
        <a>Redact</a>
        <p> Author: {{ current_user.username }} </p>
    </div>
{% endfor %}
{% if posts.has_prev %}
    <a href="{{ url_for('post.publications', page=posts.prev_num) }}">←</a>
{% endif %}
{% if posts.has_next %}
    <a href="{{ url_for('post.publications', page=posts.next_num) }}">→</a>
{% endif %}
{% endblock %}

app/templates/sign-in.html
{% extends "base.html" %}

{% block title %}Sign in{% endblock %}

{% block content %}
    <h2>Sign in</h2>
    <form method="POST">
        <label for="username">Username:</label>
        <input type="text" name="username" required>

        <label for="password">Password:</label>
        <input type="password" name="password" required>

        <button type="submit">Sign in</button>
    </form>

    <p>Don't have an account?<a href="{{ url_for('auth.sign_up') }}">Sign up</a></p>
{% endblock %}

app/templates/sign-up.html
{% extends "base.html" %}

{% block title %}Sign up{% endblock %}

{% block content %}
    <h2>Sign up</h2>
    <form method="POST">
        <label for="username">Username:</label>
        <input type="text" name="username" required>

        <label for="password">Password:</label>
        <input type="password" name="password" required>

        <button type="submit">Sign up</button>
    </form>

    <p>Already have account?<a href="{{ url_for('auth.sign_in') }}">Sign in</a></p> 
{% endblock %}